import { copyFileSync, mkdirSync, existsSync } from "node:fs";
import { join, basename } from "node:path";
import { scanGLTFPath, type GLTFDeepScanResult } from "./gltf-deep-scanner";
import type { AssetManifest, SafeActionId } from "./asset-manifest";

export type ActionCoverageState =
  | "clip_present"
  | "fallback_clip"
  | "static_fallback"
  | "css_fallback"
  | "blocked";

export type ActionCoverageEntry = {
  actionId: SafeActionId;
  state: ActionCoverageState;
  assetId: string | null;
  fallbackReason: string | null;
};

export type ActionCoverageTable = Record<SafeActionId, ActionCoverageEntry>;

export type NormalizationResult = {
  ok: boolean;
  manifest: AssetManifest | null;
  scanResult: GLTFDeepScanResult | null;
  coverageTable: ActionCoverageTable | null;
  errors: string[];
  warnings: string[];
  outputPath: string | null;
};

// Static fallback clip names (single GLB used for all actions = static fallback)
const STATIC_FALLBACK_CLIP = "idle";

function buildCoverageTable(
  manifest: AssetManifest,
  allActionsUseSameAsset: boolean
): ActionCoverageTable {
  const table: ActionCoverageTable = {} as ActionCoverageTable;

  for (const actionId of Object.keys(manifest.actions) as SafeActionId[]) {
    const action = manifest.actions[actionId];
    if (!action) {
      table[actionId] = {
        actionId,
        state: "blocked",
        assetId: null,
        fallbackReason: "action missing from manifest"
      };
      continue;
    }

    if (allActionsUseSameAsset) {
      table[actionId] = {
        actionId,
        state: "static_fallback",
        assetId: action.assetId,
        fallbackReason: "single GLB used for all actions"
      };
    } else {
      table[actionId] = {
        actionId,
        state: "clip_present",
        assetId: action.assetId,
        fallbackReason: null
      };
    }
  }

  return table;
}

export function normalizeProviderOutput(
  inputGlbPath: string,
  outputDir: string,
  options?: {
    packId?: string;
    version?: string;
    providerName?: string;
    licenseType?: string;
    licenseAttribution?: string;
  }
): NormalizationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  // Step 1: Deep scan the GLB
  const scanResult = scanGLTFPath(inputGlbPath);
  if (!scanResult.ok) {
    return {
      ok: false,
      manifest: null,
      scanResult,
      coverageTable: null,
      errors: scanResult.errors.map(e => `${e.code}: ${e.reason}`),
      warnings: scanResult.warnings.map(w => `${w.code}: ${w.reason}`),
      outputPath: null
    };
  }

  warnings.push(...scanResult.warnings.map(w => `${w.code}: ${w.reason}`));

  // Step 2: Copy GLB to output dir
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const glbFileName = basename(inputGlbPath);
  const outputPath = join(outputDir, glbFileName);

  try {
    copyFileSync(inputGlbPath, outputPath);
  } catch (err) {
    return {
      ok: false,
      manifest: null,
      scanResult,
      coverageTable: null,
      errors: [`failed to copy GLB: ${err}`],
      warnings,
      outputPath: null
    };
  }

  // Step 3: Build manifest
  const packId = options?.packId ?? `provider-${Date.now()}`;
  const version = options?.version ?? "1.0.0";
  const assetId = glbFileName.replace(/\.[^.]+$/, "");
  const displayName = `${options?.providerName ?? "Provider"} GLB Pack`;
  const fileName = glbFileName;

  // Check if all 8 core actions use the same GLB (static fallback scenario)
  // For a provider output with a single GLB, all actions point to the same asset
  const manifest = {
    schemaVersion: "5.8" as const,
    packId,
    version,
    displayName,
    rendererKind: "gltf" as const,
    license: {
      type: options?.licenseType ?? (options?.providerName ? `provider:${options.providerName}` : "unknown"),
      attribution: options?.licenseAttribution ?? `Generated by ${options?.providerName ?? "unknown provider"}`
    },
    assets: {
      [assetId]: { assetId, kind: "gltf" as const, fileName }
    },
    actions: {
      idle: { assetId, loop: true, priority: "base" as const },
      thinking: { assetId, loop: true, priority: "base" as const },
      running: { assetId, loop: true, priority: "base" as const },
      success: { assetId, loop: false, priority: "transient" as const, durationMs: 3000 },
      warning: { assetId, loop: false, priority: "transient" as const, durationMs: 4000 },
      error: { assetId, loop: false, priority: "urgent" as const, durationMs: 6000 },
      need_input: { assetId, loop: false, priority: "urgent" as const, durationMs: 8000 },
      sleeping: { assetId, loop: true, priority: "base" as const }
    }
  } as unknown as AssetManifest;

  // Step 4: Build coverage table
  // All actions map to the same single GLB = static_fallback coverage
  const coverageTable = buildCoverageTable(manifest, true);

  return {
    ok: true,
    manifest,
    scanResult,
    coverageTable,
    errors,
    warnings,
    outputPath
  };
}

export function validateCoverageTable(
  table: ActionCoverageTable
): { ok: boolean; blockedActions: SafeActionId[] } {
  const blockedActions: SafeActionId[] = [];

  for (const [actionId, entry] of Object.entries(table) as [SafeActionId, ActionCoverageEntry][]) {
    if (entry.state === "blocked") {
      blockedActions.push(actionId);
    }
  }

  return { ok: blockedActions.length === 0, blockedActions };
}
